### ISSUE TITLE
uninitialized constant Chef::Resource::CephClient

### ISSUE THREAD

**Issue by anthonyryan** [ceph/ceph-chef#4]
I'm getting this error with Chef 12 after changing one of the client creations for mds. 
 ```
NameError
---------
uninitialized constant Chef::Resource::CephClient
 
Cookbook Trace:
---------------
/var/chef/cache/cookbooks/ceph-chef/providers/client.rb:60:in `load_current_resource'
 
Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/ceph-chef/recipes/mds.rb
 
33: ceph_chef_client 'mds' do
34:   caps('osd' => 'allow *', 'mon' => 'allow rwx')
35:   keyname "mds.#{node['hostname']}"
36:   filename "/var/lib/ceph/mds/#{cluster}-#{node['hostname']}/keyring"
37: end
38: 
 
Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/ceph-chef/recipes/mds.rb:33:in `from_file'
 
ceph_chef_client("mds") do
action [:add]
retries 0
retry_delay 2
default_guard_interpreter :default
declared_type :ceph_chef_client
cookbook_name "ceph-chef"
recipe_name "mds"
caps {"osd"=>"allow *", "mon"=>"allow rwx"}
keyname "mds.proxy1"
filename "/var/lib/ceph/mds/ceph-proxy1/keyring"
end

providers/client.rb:
def load_current_resource
  @current_resource = Chef::Resource::CephClient.new(@new_resource.name)
  @current_resource.name(@new_resource.name)
  @current_resource.as_keyring(@new_resource.as_keyring)
  @current_resource.keyname(@new_resource.keyname || "client.#{@new_resource.name}.#{node['hostname']}")
  @current_resource.caps(get_caps(@current_resource.keyname))
  default_filename = "/etc/ceph/ceph.client.#{@new_resource.name}.#{node['hostname']}.#{@new_resource.as_keyring ? 'keyring' : 'secret'}"
  @current_resource.filename(@new_resource.filename || default_filename)
  @current_resource.key(get_key(@current_resource.keyname))
  @current_resource.caps_match = @current_resource.caps == @new_resource.caps
  @current_resource.keys_match = @new_resource.key.nil? || (@current_resource.key == @new_resource.key)
  @current_resource.exists = ! (@current_resource.key.nil? || @current_resource.key.empty?)
end
```

**Comment by cloudm2** [comment]
Are you implementing CephFS? The CephFS testing in not complete. If you're doing mainly Object Store then take a look at github.com/bloomberg/chef-bcs. It goes through the correct order. We have put more into Object Store to start with and then Block followed by CephFS. We are also beginning more testing on Infernelis/Jewel release next week. hx

**Comment by cloudm2** [comment]
Thx

**Comment by cloudm2** [comment]
Also, it appears that this issue fell through through crack so sorry about that! If you would like to take a go at it and issue a PR that would be great :).

**Comment by cloudm2** [comment]
Old issue - closing. Thanks
